### ISSUE TITLE
NoSuchFieldError: _super

### ISSUE THREAD

**Issue by amadornes** [dmillerw/ASMTemplates#3]
I'm getting a NoSuchFieldError exception every time I try to call a method in _super from the template. Is it not implemented yet or...?

**Comment by Dynious** [comment]
That should work. Could you show the template class and how you use it?

**Comment by amadornes** [comment]
MyClass (the class I want to expand on):

``` java
public class MyClass {
    public void say(String text) {
        System.out.println(text);
    }
}
```

TShouting (the template):

``` java
public class TShouting extends Template<MyClass> {
    @MOverride
    public void say(String text) {
        _super.say(text.toUpperCase());
    }
}
```

When I create a class based on MyClass with the template TShouting, and call the say() method, I get the NoSuchFieldError I was talking about before. (I used to have and object as the argument in the template and used @MCastParam to cast it to the correct type, but it didn't work either)

**Comment by Dynious** [comment]
I'm now able to reproduce this, but I do not know why I suddenly get this error.

**Comment by Dynious** [comment]
More info:

In the class where I got this error ASMTemplates also failed to override this method in this class:

https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/block/BlockAlchemicalChest.java#L36

Code to override the method (in the Template file):

```
    @MOverride
    public TileEntity createNewTileEntity(World world, int metaData)
    {
        try
        {
            return RefinedRelocation.blockToSortingTile.get(_super)[metaData].newInstance();
        } catch (Exception e)
        {
            e.printStackTrace();
        }
        return null;
    }
```

Log:

```
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Found super-class constructor: {name: <init>, signature: ()}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Found annotated field in template: {name: name, signature: Ljava/lang/String;}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Found template constructor: {name: construct, signature: ()}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Overridding method: {name: onBlockActivated, signature: (Lnet/minecraft/world/World;IIILnet/minecraft/entity/player/EntityPlayer;IFFF)Z}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Overridding method: {name: getUnlocalizedName, signature: ()Ljava/lang/String;}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Overridding method: {name: createNewTileEntity, signature: (Lnet/minecraft/world/World;I)Lnet/minecraft/tileentity/TileEntity;}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Failed to override public net.minecraft.tileentity.TileEntity com.dynious.refinedrelocation.mods.AutoSortingBlockTemplate.createNewTileEntity(net.minecraft.world.World,int)
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Found matching super constructor in template: {name: construct, signature: ()}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Found super call to overridden method!
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Redirected super call!
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG:  * OLD: GETFIELD {owner: com/dynious/refinedrelocation/mods/AutoSortingBlockTemplate, name: _super, desc: Ljava/lang/Object;}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG:  * NEW: INVOKESPECIAL {owner: com/pahimar/ee3/block/BlockAlchemicalChest_GENERATED_544718633, name: default_getUnlocalizedName, desc: ()Ljava/lang/String;}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Skipping {CHECKCAST net/minecraft/block/Block} 2 left.
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Skipping {INVOKEVIRTUAL {owner: net/minecraft/block/Block, name: getUnlocalizedName, desc: ()Ljava/lang/String;}} 1 left.
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Redirected super call!
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG:  * OLD: GETFIELD {owner: com/dynious/refinedrelocation/mods/AutoSortingBlockTemplate, name: _super, desc: Ljava/lang/Object;}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG:  * NEW: GETSTATIC {owner: com/pahimar/ee3/block/BlockAlchemicalChest_GENERATED_544718633, name: tabRefinedRelocation, desc: Lnet/minecraft/creativetab/CreativeTabs;}
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Skipping {CHECKCAST net/minecraft/block/Block} 2 left.
[20:05:57] [Client thread/INFO] [STDOUT]: [dmillerw.asm.core.SubclassGenerator:debug:43]: DEBUG: Skipping {GETSTATIC {owner: com/dynious/refinedrelocation/RefinedRelocation, name: tabRefinedRelocation, desc: Lnet/minecraft/creativetab/CreativeTabs;}} 1 left.
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchFieldError: _super
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.pahimar.ee3.block.BlockAlchemicalChest_GENERATED_544718633.<init>(.dynamic:24)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Class.newInstance(Class.java:374)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.dynious.refinedrelocation.RefinedRelocation.postInit(RefinedRelocation.java:151)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:606)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:606)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:606)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.startGame(Minecraft.java:586)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.Minecraft.run(Minecraft.java:931)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.client.main.Main.main(Main.java:164)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:606)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:78)
[20:05:57] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at GradleStart.main(GradleStart.java:45)
```

NOTE: It is very possible that this has nothing to do with this.

EDIT:
My Template is of type Block, not BlockContainer. The method isn't implemented in the type used in the template. Probably doesn't matter, but every little bit of info might help.

**Comment by dmillerw** [comment]
Acknowleding. Will poke at it tomomorrow. Need sleep;
